Add test case

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -4,6 +4,10 @@ try() {
   input="$2"
 
   ./bin/gocc "$input" > tmp.s
+  if [ "$?" != "0" ]; then
+    echo "gocc failed"
+    exit 1
+  fi
   gcc -o tmp tmp.s
   ./tmp
   actual="$?"
@@ -32,5 +36,7 @@ try 1 '(3 * -1) / +3 + 2 *(-1) * (-1)'
 try 1 '-1 * 3 + 4'
 try 0 '0==1'
 try 1 '42==42'
+try 1 '31>15'
+try 0 '31<15'
 
 echo OK
